#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "No policy arn provided."
    exit 1
fi

if [ -z "$2" ]; then
    echo "No policy document provided."
    exit 1
fi

POLICY_ARN="$1"
POLICY_DOC="$2"

aws iam create-policy-version \
    --policy-arn "$POLICY_ARN" \
    --policy-document "$POLICY_DOC" \
    --set-as-default
