#!/usr/bin/env bash
echo "== delete-bucket"

if [ -z "$1" ]; then
    echo "No bucket was provided."
    exit 1
fi

BUCKET_NAME="$1"

aws s3api delete-bucket --bucket "$BUCKET_NAME"
echo "\"$BUCKET_NAME\" successfully deleted."
