#!/usr/bin/env bash
echo "== list objects" >&2

if [ -z "$1" ]; then
    echo "No bucket was provided."
    exit 1
fi

BUCKET_NAME="$1"

aws s3api list-objects-v2 \
    --bucket "$BUCKET_NAME" \
    --query Contents[].Key
