#!/usr/bin/env bash

# Check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided."
    exit 1
fi

BUCKET_NAME="$1"

# Check for filename prefix
if [ -z "$2" ]; then
 echo "No file prefix was provided."
 exit 1
fi

FILE_PREFIX="$2"

# Where to store files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# Remove folder if exists
rm -r "$OUTPUT_DIR"

mkdir -p "$OUTPUT_DIR"

# Random number of files to create
NUM_FILES="$((RANDOM % 6 + 5))"

for ((i=1; i<="$NUM_FILES"; i++)); do
    FILE_NAME="$OUTPUT_DIR/${FILE_PREFIX}_$i.txt"

    dd if=/dev/urandom of="$FILE_NAME" bs=1024 count="$((RANDOM % 1024 + 1))" 2>/dev/null
done

tree "$OUTPUT_DIR"

aws s3 sync "$OUTPUT_DIR" s3://"$BUCKET_NAME"/files
