#!/usr/bin/env bash
echo "== deploy s3 bucket via cfn"

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
    --template-file template.yaml \
    --no-execute-changeset \
    --stack-name $STACK_NAME
